### ISSUE TITLE
How to compute when there're NA?

### ISSUE THREAD

**Issue by huosan0123** [bmbolstad/preprocessCore#4]
Thanks for your  fantasitic work. I am going to rewrite your normalize.quantiles.R in python. So I am wondering how you handle NAs in pandas.  I have read your code, but I didn't have a clue. So, could you make it clear step by step?  A example is much more appreciated!

**Comment by bmbolstad** [comment]
questions of how to handle NA in pandas/python are outside the scope of preprocessCore.

Really the best way to understand is to spend more time reading the code. I admit it might be hard to decipher but my suggestion is to try to just read the buts that are used when PTHREADS is not enabled.

But briefly speaking, the idea is to treat the the NA values as arising from some process such that they are missing at random, rather than arising via truncation or some other mechanism. Thus the idea is that you estimate the empirical distribution based on the non-NA data alone.

Suppose there are M rows in your matrix and N columns. To get the target distribution you average the quantiles across the columns of observed data. So you need to compute the quantiles for each column. For a given column If nothing is NA then this is simply the sorted observations, while if there are NA values then you need to estimate M quantiles based on the M_nonna observed. If you follow the code closely you’ll see this is done by sorting the non-NA values, then using interpolation to determine the correct quantiles.

When using the target to actually do the normalization a similar interpolation trick is used for columns where missing values (NA) are present.

**Comment by huosan0123** [comment]
After reading your qnorm.c code thoroughly, I understood how it works. **Thanks!** 
To be honest, https://github.com/huosan0123/preprocessCore/blob/master/src/qnorm.c#L1801~1849， these lines are really complicated to understand.
